version: '3'
volumes:
  mqtt_data:


services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - mqtt_data:/mosquitto/data/
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    logging:
      options:
        max-size: '10m'
        max-file: '5'
      driver: json-file
    mem_limit: 200m

  weather-producer:
    container_name: weather-producer
    build: .
    restart: always
    command: ["python3", "/opt/src/weather_producer_main.py"]
    volumes:
      - "./results/weather.txt:/opt/output/weather.txt"
    logging:
      options:
        max-size: '10m'
        max-file: '5'
      driver: json-file
    mem_limit: 200m
    env_file:
      - .env
    depends_on:
      - mosquitto

  weather-consumer:
    container_name: weather-consumer
    build: .
    restart: always
    command: ["python3", "/opt/src/weather_consumer_main.py"]
    volumes:
      - "./results/weather.csv:/opt/output/weather.csv"
    logging:
      options:
        max-size: '10m'
        max-file: '5'
      driver: json-file
    mem_limit: 200m
    depends_on:
      - mosquitto
